# permissions for end users to view stuckpodsnotifiers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: stuckpodnotifier
    app.kubernetes.io/managed-by: kustomize
  name: stuckpodsnotifier-viewer-role
rules:
- apiGroups:
  - monitor.my.domain
  resources:
  - stuckpodsnotifiers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitor.my.domain
  resources:
  - stuckpodsnotifiers/status
  verbs:
  - get
